name: update minecraft version 

on:
  schedule:
    - cron: "0 0 * * *"  # Schedule the workflow to run daily
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up Git user
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Get Latest Minecraft Version
        id: get_version
        run: |
          response=$(curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json)
          latest_version=$(echo "$response" | jq -r .latest.release)
          echo "::set-output name=latest_version::$latest_version"

      - name: Update stored_version.txt
        run: |
          # Fetch the latest changes from the main branch
          git fetch origin main || :

          # Rebase the changes on top of the latest main branch
          git rebase origin/main || :

          # Check if there are changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update stored_version.txt to ${{ steps.get_version.outputs.latest_version }}"
          fi
          
          # Fetch again to make sure there are no new changes
          git fetch origin main
          
          # If any new changes, rebase and resolve conflicts if necessary
          git rebase origin/main
          
          # Push changes to the main branch and set exit code
          git push origin main || exit 1
